services:
  mysql:
    image: mysql:9.7.1 
    container_name: demo-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: xml-web-service

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 10

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: tranbach2907/trainning-project-xml-web-service:latest
    container_name: xml-web-service-app
    restart: always

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_APPLICATION_NAME: demo

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/xml_web_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

volumes:
  mysql_data: